### ISSUE TITLE
Winner Not Announced

### ISSUE THREAD

**Issue by jamrsim** [r-carroll/travel-bingo#1]
After selecting, Reset Board, from the hamburger menu, regardless of how many squares are selected, a winner is never announced. 

Expected behavior, when five squares in a line are selected, a winner is announced.

**Comment by r-carroll** [comment]
> After selecting, Reset Board, from the hamburger menu, regardless of how many squares are selected, a winner is never announced.
> 
> Expected behavior, when five squares in a line are selected, a winner is announced.

Does this only happen if you've previously selected `return to board` after a victory?

In other words: normal play -> bingo -> return to board -> reset board -> new bingo -> winner not announced

**Comment by jamrsim** [comment]
Yes, I believe that is correct.
